---
chargen:
  approval_message: Congratulations!  Your application has been approved.  Type %xhonstage%xn
    to go forth and RP.  You may want to customize your character profile on the web
    portal.
  rejection_message: Sorry, your character could not be approved at the present time
    for the reasons described below.  Please see %xhhelp app%xn for help making changes
    and resubmitting, and contact the person handling your application if you have
    any questions.
  post_approval_message: Please make sure they have a profile image for their log
    icon.
  welcome_message: Please welcome %{name}!
  hooks_required: true
  arrivals_board: New Arrivals
  app_category: APP
  app_resubmit_status: OPEN
  app_hold_status: HOLD
  stages:
    start:
      tutorial: chargen.md
    app:
      tutorial: app command.md
    sheet:
      help: sheets
    demographics:
      help: demographics
    groups:
      help: groups
    ranks:
      help: ranks
    background:
      help: backgrounds
    abilities:
      help: skills
    desc:
      help: descriptions
    hooks:
      help: hooks
    handles:
      help: handles
    profile:
      help: profile
    lastwill:
      help: idle_out
    review:
      help: apps
  shortcuts:
    chargen: cg
    cg/back: cg/prev
    cg/previous: cg/prev
    bg/approve: app/approve
    bg/reject: app/reject
    bg/submit: app/submit
    bg/unsubmit: app/unsubmit
    hooks: hook
    hook/delete: hook/remove
    hook/add: hook/set
  bg_blurb: 'Backgrounds should cover the basics of who your character is and how they have ended up here. Some things to think about:'
  hooks_blurb: RP Hooks are interesting things about your character that others can hook into for RP. This could be a reputation your character has, a job, a family connection, or anything else that might inspire someone to connect with you. Looking around at other characters' sheets can be a good way to get inspiration for RP Hooks.
  desc_blurb: Set both your main description, visible when people look at
    you, and a short description that shows your character at a glance.
