---
magic-items:
  Blessing Of Wisakedjak:
    name: Blessing Of Wisakedjak
    desc: A six-point deer antler with one tip jaggedly broken off. The base is wrapped and bound in leather that ends in a loop, perfect for attaching to a belt. It grants its owner the ability to cast the Level 6 Nature spell Half Shift, allowing them to transform a portion of their body into a Jenu.
    spell: Half Shift (Jenu)
  Rosewing:
    name: Rosewing
    desc: 'An 8 3/4" long magic wand made of Oak with inlaid Rose Quartz detailing and a Pink Sapphire hilt ornament carved into a sharp many-pointed star. All spells cast with this magic device manifest with benign twinkling specks of blush-colored light. Gives +1 to spellcasting.'
    spell_mod: 1
  Soul Stone Ring:
    name: Soul Stone Ring
    desc: A pair of thick bronze rings each set with a single round opalescent stone. The stone changes color to indicate shifts in the emotional status of whoever sports its mate. When worn, the magic infused in the object allows the user to experience the other wearer's condition for his or her self. An excellent way to keep tabs on allies, loved ones, and mortal enemies.
  Skofnung:
    name: Skofnung
    desc: Ragnar's magical sword with a soul inside.
  Konvaskr:
    name: Konvaskr
    desc: A flying ship that really needs a better desc.
