---
magic-items:
  Blessing Of Wisakedjak:
    name: Blessing Of Wisakedjak
    desc: This item grants its owner the ability to cast the Level 6 Nature spell, Enhanced Limbs.
    spell: Enhanced Limbs
  Rosewing:
    name: Rosewing
    desc: 'An 8 3/4" long magic wand made of Oak with inlaid Rose Quartz detailing and a Pink Sapphire hilt ornament carved into a sharp many-pointed star. All spells cast with this magic device manifest with benign twinkling specks of blush-colored light. Gives +1 to spellcasting.'
    spell_mod: 1
