---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: name
    width: 20
    title: Name
  - field: major_school
    width: 8
    title: Major
  - field: minor_school
    width: 8
    title: Minor
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
